accounts/urls.py
from django.urls import path,include
from . import views

app_name = 'accounts'

urlpatterns = [
    # path('',views.index,name='index'),
    path('<int:user_pk>/',views.detail,name='detail'),
    path('signup/',views.signup,name='signup'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

movies/urls.py
from django.urls import path
from . import views


app_name = "movies"
urlpatterns = [
    path('', views.index,name='index'),
    path('<int:movie_id>/', views.detail,name='detail'),
    path('<int:movie_id>/reviews/new/', views.review_new, name='review_new'),
    path('<int:movie_id>/reviews/<int:review_id>/review_delete/', views.review_delete, name='review_delete'),
    path('<int:movie_id>/like/', views.like, name='like'),
    path('<int:movie_id>/score/', views.score, name='score'),
    path('search/', views.search, name='search')
]

pjt/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
urlpatterns = [
    path('',views.index),
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
]

movies/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator
# Create your models here.

class Genre(models.Model):
    name = models.CharField(max_length=20)

class Movie(models.Model):
    title = models.CharField(max_length=30)
    poster_url = models.CharField(max_length=140)
    description = models.TextField()
    genres = models.ManyToManyField(
        Genre,
        related_name='movies_genre',
        blank=True
    )
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='like_movies',
        blank=True
    )
    rate_avg = models.FloatField()
    release_date = models.DateField()
    movie_id = models.IntegerField()
    grade = models.IntegerField()
    view_img = models.CharField(max_length=140)
    rate_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='rate_movies',
        through='Score',
        blank=True
    )

class Score(models.Model):
    score = models.IntegerField(default=0)
    user  = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie,on_delete=models.CASCADE)
    

class Review(models.Model):
    content = models.CharField(max_length=140)
    movie = models.ForeignKey(Movie,on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

movies/forms.py
from .models import Review, Score
from django import forms

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        exclude = ('user','movie')
class ScoreForm(forms.ModelForm):
    class Meta:
        model = Score
        exclude = ('user','movie')

movies/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Movie,Review, Score, Genre
from .forms import ReviewForm, ScoreForm
from accounts.models import User
from django.http import HttpResponseForbidden, HttpResponse

from django.http import JsonResponse
import json
import requests


flag = 0
movie_list_1 = []
recommend_tmp = []
user_tmp = ''
# simil 함수 유저가 준 점수 평균
def simil(u1, u2):
    movies = Movie.objects.all()
    S, S_u1, S_u2 =0,0,0
    for movie in movies:
        if u1 in movie.rate_users.all() and u2 in movie.rate_users.all():
            r1 = Score.objects.filter(movie_id = movie.id, user_id =u1.id)[0].score
            r2 = Score.objects.filter(movie_id = movie.id, user_id =u2.id)[0].score
            S += (r1-u1.rate)*(r2-u2.rate)
            S_u1 += (r1-u1.rate)**2
            S_u2 += (r2-u2.rate)**2
    try:
        return S/((S_u1**0.5)*(S_u2**0.5))
    except:
        return 0
# rating 함수
def rating(movie, user, cmp_users):
    S,abs_S = 0,0
    for cmp_user in cmp_users:
        if cmp_user not in movie.rate_users.all(): continue
        result = simil(user,cmp_user)
        r = Score.objects.filter(movie_id = movie.id, user_id = cmp_user.id)[0].score
        S += (result)*(r-cmp_user.rate)
        abs_S += abs(result)
    try:
        return user.rate + S/abs_S
    except:
        return user.rate
def solve(user):
    users = User.objects.all()
    movies = Movie.objects.all()
    tmps = []
    cmp_users = []
    for tmp in users:
        if user == tmp: continue
        cmp_users.append((simil(user, tmp), tmp))
    cmp_users.sort(key=lambda x: x[0],reverse=True)
    for i in range(5):
        tmps.append(cmp_users[i][1])
    cmp_movies = []
    for movie in movies:
        if movie in user.rate_movies.all(): continue
        cmp_movies.append((rating(movie,user,tmps),movie))
    cmp_movies.sort(key=lambda x: x[0],reverse=True)
    recommend = []
    for i in range(10):
        recommend.append(cmp_movies[i][1])
    return recommend
# Create your views here.
def index(request):
    movies = Movie.objects.all()
    user = request.user
    genres = Genre.objects.all()
    recommend = []
    global movie_list_1,recommend_tmp
    global flag,user_tmp
    if flag:
        movie_list = movie_list_1
    elif not flag:
        movie_list = [[] for _ in range(18)]
        for movie in movies:
            if movie.genres.all().filter(pk=28) and len(movie_list[0])<20:
                movie_list[0].append(movie)
            if movie.genres.all().filter(pk=12) and len(movie_list[1])<20:
                movie_list[1].append(movie)
            if movie.genres.all().filter(pk=16) and len(movie_list[2])<20:
                movie_list[2].append(movie)
            if movie.genres.all().filter(pk=35) and len(movie_list[3])<20:
                movie_list[3].append(movie)
            if movie.genres.all().filter(pk=80) and len(movie_list[4])<20:
                movie_list[4].append(movie)
            if movie.genres.all().filter(pk=99) and len(movie_list[5])<20:
                movie_list[5].append(movie)
            if movie.genres.all().filter(pk=18) and len(movie_list[6])<20:
                movie_list[6].append(movie)
            if movie.genres.all().filter(pk=10751) and len(movie_list[7])<20:
                movie_list[7].append(movie)
            if movie.genres.all().filter(pk=14) and len(movie_list[8])<20:
                movie_list[8].append(movie)
            if movie.genres.all().filter(pk=36) and len(movie_list[9])<20:
                movie_list[9].append(movie)
            if movie.genres.all().filter(pk=27) and len(movie_list[10])<20:
                movie_list[10].append(movie)
            if movie.genres.all().filter(pk=10402) and len(movie_list[11])<20:
                movie_list[11].append(movie)
            if movie.genres.all().filter(pk=9648) and len(movie_list[12])<20:
                movie_list[12].append(movie)
            if movie.genres.all().filter(pk=10749) and len(movie_list[13])<20:
                movie_list[13].append(movie)
            if movie.genres.all().filter(pk=878) and len(movie_list[14])<20:
                movie_list[14].append(movie)
            if movie.genres.all().filter(pk=53) and len(movie_list[15])<20:
                movie_list[15].append(movie)
            if movie.genres.all().filter(pk=10752) and len(movie_list[16])<20:
                movie_list[16].append(movie)
            if movie.genres.all().filter(pk=37) and len(movie_list[17])<20:
                movie_list[17].append(movie)
            flag = 1
            movie_list_1 = movie_list
    if request.user.is_authenticated and len(user.rate_movies.all())>=10:
        if recommend_tmp == [] or user_tmp != request.user:
            recommend = solve(user)
            recommend_tmp = recommend
            user_tmp = request.user
        else:
            recommend = recommend_tmp
    else:
        for movie in movies:
            if request.user.is_authenticated and movie in user.rate_movies.all(): continue
            S,cnt = 0,0
            for tmp in movie.rate_users.all():
                cnt+=1
                S+=Score.objects.filter(movie_id = movie.id, user_id = tmp.id)[0].score
            try:
                recommend.append((S/cnt,movie))
            except:
                recommend.append((0,movie))
        recommend.sort(key=lambda x: x[0],reverse=True)
        reco = []
        for i in range(10):
            reco.append(recommend[i][1])
        recommend = reco
    context = {
        'movies' : movies,
        'recommend' : recommend,
        'genres' : genres,
        'actions' : movie_list[0],
        'advs' : movie_list[1],
        'anis' : movie_list[2],
        'comis' : movie_list[3],
        'guls' : movie_list[4],
        'docus' : movie_list[5],
        'dramas' : movie_list[6],
        'fams' : movie_list[7],
        'fans' : movie_list[8],
        'his' : movie_list[9],
        'afrs' : movie_list[10],
        'musics' : movie_list[11],
        'mis' : movie_list[12],
        'romans' : movie_list[13],
        'SFs' : movie_list[14],
        'thrils' : movie_list[15],
        'wars' : movie_list[16],
        'wests' : movie_list[17],
    }
    return render(request,"movies/index.html",context)

def detail(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    url = f'https://api.themoviedb.org/3/movie/{movie.movie_id}/videos?language=ko-KR&api_key=5e886c8bf9b218d5e7c201655a0015ec'
    r = requests.get(url)
    data = json.loads(r.text)
    movie_dict = data["results"]
    if movie_dict:
        token = movie_dict[0]['key']
        teaser = f'https://www.youtube.com/embed/{token}'
    else:
        teaser = ''
    review_form = ReviewForm()
    score_form = ScoreForm()
    reviews = Review.objects.filter(movie_id=movie_id)
    scores = Score.objects.filter(movie_id=movie_id)
    if request.user.is_authenticated:
        if request.user in movie.rate_users.all():
            score = scores.filter(user_id=request.user.id)[0].score
        else:
            score = 0
    else:
        score = 0
    try:
        review_avg = sum(map(lambda x: x.score,reviews))/len(reviews)
    except:
        review_avg = 0
    # print(reviews)
    # print(review_sum)
    context = {
        'movie' : movie,
        'review_form' : review_form,
        'review_avg' : review_avg,
        'score_form' : score_form,
        'scores' : scores,
        'myscore' : score,
        'teaser' : teaser
    }
    return render(request, "movies/detail.html", context)

@require_POST
def review_new(request,movie_id):
    if request.user.is_authenticated:
        movie = get_object_or_404(Movie,pk=movie_id)
        review_form = ReviewForm(request.POST)
        if review_form.is_valid():
            form = review_form.save(commit=False)
            form.user = request.user
            form.movie = movie
            form.save()
            return redirect('movies:detail',movie_id)
        else:
            messages.info(request,'0~5사이의 값을 입력하세요')
            return redirect('movies:detail',movie_id)
    else:
        return redirect('accounts:login')
@require_POST
def review_delete(request, movie_id,review_id):
    review = get_object_or_404(Review,pk=review_id)
    review.delete()
    return redirect('movies:detail',movie_id)

@login_required
def like(request, movie_id):
    if request.is_ajax():
        movie = get_object_or_404(Movie, pk=movie_id)
        user = request.user
        is_liked = True
        if user in movie.like_users.all():
            movie.like_users.remove(user)
            is_liked = False
        else:
            movie.like_users.add(user)
            is_liked = True
        count = movie.like_users.count()
        return JsonResponse({'is_liked':is_liked,'count':count})
    else:
        return HttpResponseForbidden()

@require_POST
def score(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    user = request.user
    if user.is_authenticated:
        score_form = ScoreForm(request.POST)
        if score_form.is_valid():
            score = Score.objects.filter(movie_id = movie_id, user_id = request.user.id)
            score.delete()
            score_form = ScoreForm(request.POST)
            form = score_form.save(commit=False)
            form.user = request.user
            form.movie = movie
            form.save()
            S = 0
            cnt = 0
            for user in movie.rate_users.all():
                cnt+=1
                S +=Score.objects.filter(movie_id = movie_id, user_id = user.id)[0].score
            movie.rate_avg = S/cnt
            movie.save()
            S = 0
            cnt = 0
            for movie in user.rate_movies.all():
                cnt+=1

movies/templates/_navbar.html
<header>
  <nav class="Jua navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/movies/">SoulLess</a>
    <p class></p>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav mr-auto">
        {% if user.is_authenticated %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'accounts:detail' user.pk %}">MyPage</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:logout'%}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:signup'%}">SignUp</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:login'%}">Login</a>
        </li>
        {% endif %}
      </ul>
      <span class="navbar-text text-light">
        <form action="{% url 'movies:search' %}" class="form-inline" method="GET">
          {% if user.is_authenticated %}
          <span>{{ user.username }}님 반갑습니다. </span>
          {% endif %}
          <input class="form-control mr-sm-2" type="search" placeholder="영화,장르,유저 검색" aria-label="Search" name='search'>
          <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search</button>
        </form>
      </span>
    </div>
  </nav>
</header>

movies/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">
    <link href="https://fonts.googleapis.com/css?family=Black+Han+Sans|East+Sea+Dokdo|Jua|Noto+Sans+KR&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/swiper/css/swiper.css">
    <link rel="stylesheet" href="https://unpkg.com/swiper/css/swiper.min.css">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <style>
        header {
            position: sticky;
            top: 0;
            z-index: 1000;
        }

        .movie_index_font {
            font-family: 'Jua', sans-serif;
            color: #ffffff;
            text-shadow: 10px 10px 10px #000000;
        }

        .my-image {
            width: 250px;
            height: 400px;
        }

        .target {
            display: inline-block;
            width: 400px;
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis;
            white-space: normal;
            line-height: 1.2;
            height: 3.6;
            text-align: left;
            word-wrap: break-word;
            display: -webkit-box;
            -webkit-line-clamp: 4;
            -webkit-box-orient: vertical;
        }

        .big {
            -webkit-transition: width 2s;
            /* For Safari 3.1 to 6.0 */
            transition: width 2s;
        }

        .big {
            width: 340px;
            height: 450px;
        }

        .image-container {
            position: relative;
            display: inline-block;
        }

        .image-grey {
            display: block;
            -webkit-filter: grayscale(100%);
        }

        .image-container:after {
            position: absolute;
            content: "";
            top: 0;
            left: 50%;
            width: 50%;
            height: 100%;
            background-image:url({{movie.view_img}});
            background-position: top right;
        }

        .BHS {
            font-family: 'Black Han Sans', sans-serif;
        }

        .Jua {
            font-family: 'Jua', sans-serif;
        }

        .ESD {
            font-family: 'East Sea Dokdo', cursive;
        }

        .Noto {
            font-family: 'Noto Sans KR', sans-serif;
        }

        #loading {
            width: 100%;
            height: 100%;
            top: 0px;
            left: 0px;
            position: fixed;
            display: block;
            opacity: 0.3;
            background-color: #fff;
            z-index: 99;
            text-align: center;
        }

        #loading-image {
            position: absolute;
            top: 50%;
            left: 50%;
            z-index: 100;
        }
    </style>
    {% block css %}{% endblock %}
</head>

<body>
    <div id="loading"><img id="loading-image" src="{% static 'images/ajax-loader.gif'%}" alt="Loading..." /></div>
    {% include '_navbar.html' %}
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %}" role="alert">
        {{ message.message }}
    </div>
    {% endfor %}
    {% endif %}

    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %}">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    {% block body %}
    {% endblock %}
    </div>


    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js'%}"></script>
    <script src="https://kit.fontawesome.com/54e342cbc4.js" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/swiper/js/swiper.js"></script>
    <script src="https://unpkg.com/swiper/js/swiper.min.js"></script>

    {% block script %}
    {% endblock %}

    <script>
        $(window).on('load', function () {
            console.log('hi')
            $('#loading').hide();
        });
    </script>
</body>
</html>