accounts/urls.py
from django.urls import path,include
from . import views

app_name = 'accounts'

urlpatterns = [
    # path('',views.index,name='index'),
    path('<int:user_pk>/',views.detail,name='detail'),
    path('signup/',views.signup,name='signup'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

movies/urls.py
from django.urls import path
from . import views


app_name = "movies"
urlpatterns = [
    path('', views.index,name='index'),
    path('<int:movie_id>/', views.detail,name='detail'),
    path('<int:movie_id>/reviews/new/', views.review_new, name='review_new'),
    path('<int:movie_id>/reviews/<int:review_id>/review_delete/', views.review_delete, name='review_delete'),
    path('<int:movie_id>/like/', views.like, name='like'),
    path('<int:movie_id>/score/', views.score, name='score'),
    path('search/', views.search, name='search')
]

pjt/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
urlpatterns = [
    path('',views.index),
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser
# Create your models here.
class User(AbstractUser):
    followers = models.ManyToManyField(
                    settings.AUTH_USER_MODEL, 
                    related_name='followings',
                    blank=True
                    )
    rate = models.FloatField(default=0)
    recommend = models.BooleanField(default=False)

movies/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator
# Create your models here.

class Genre(models.Model):
    name = models.CharField(max_length=20)

class Movie(models.Model):
    title = models.CharField(max_length=30)
    poster_url = models.CharField(max_length=140)
    description = models.TextField()
    genres = models.ManyToManyField(
        Genre,
        related_name='movies_genre',
        blank=True
    )
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='like_movies',
        blank=True
    )
    rate_avg = models.FloatField()
    release_date = models.DateField()
    movie_id = models.IntegerField()
    grade = models.IntegerField()
    view_img = models.CharField(max_length=140)
    rate_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='rate_movies',
        through='Score',
        blank=True
    )

class Score(models.Model):
    score = models.IntegerField(default=0)
    user  = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie,on_delete=models.CASCADE)
    

class Review(models.Model):
    content = models.CharField(max_length=140)
    movie = models.ForeignKey(Movie,on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

class ChangeUserForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username','email','first_name','last_name')

accounts/views.py
from django.shortcuts import render,redirect, get_object_or_404
from .models import User
from .forms import ChangeUserForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.http import HttpResponseForbidden
# Create your views here.

# def index(request):
#     users = User.objects.all()

#     context = {
#         'users' : users
#     }
#     return render(request,'accounts/index.html',context)

def detail(request,user_pk):
    user = User.objects.get(pk=user_pk)
    context = {
        'puser':user
    }
    return render(request,'accounts/detail.html', context)

def signup(request):
    if request.method == 'POST':
        form = ChangeUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.recommend = True
            user.save()
            auth_login(request,user)
            return redirect('movies:index')
    else:
        form = ChangeUserForm()
    context = {
        'form' : form
    }
    return render(request,'accounts/signup.html',context)

def login(request):
    if request.method=='POST':
        form = AuthenticationForm(request,request.POST)
        if form.is_valid():
            user = form.get_user()
            user.recommend = True
            user.save()
            auth_login(request,user)
            return redirect('movies:index')
    else:
        form = AuthenticationForm()
    context = {
        'form' : form
    }
    return render(request,'accounts/login.html',context)

def logout(request):
    user = request.user
    user.recommend = False
    user.save()
    auth_logout(request)
    return redirect('movies:index')

@login_required
def follow(request, user_pk):
    if request.is_ajax():
        user = get_object_or_404(User, pk=user_pk)
        is_followed = True
        if request.user in user.followings.all():
            user.followings.remove(request.user)
            is_followed = False
        else:
            user.followings.add(request.user)
            is_followed = True
        count = user.followings.count()
        return JsonResponse({'is_followed':is_followed,'count':count})
    else:
        return HttpResponseForbidden()

accounts/templates/accounts/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
<div class="container BHS">
  <div>
    <h2 class="BHS">{{puser.username}}</h2>
    <p>Name : {{puser.last_name}} {{puser.first_name}}</p>
    <p>email : {{puser.email}}</p>
  </div>
  <div class="row divider text-center">
    <div class="col-2 emphasis">
      <h2><strong class="BHS">{{puser.followings.all.count}}</strong></h2>
      <p><small>Followers</small></p>
    </div>
    <div class="col-2 emphasis">
      <h2><strong class="BHS">{{puser.followers.all.count}}</strong></h2>
      <p><small>Followings</small></p>
    </div>
  </div>
  {% if user == puser %}
  {% if user. %}{% endif %}
  {% else %}
  <div style="width:30%">
    {% if user in puser.followings.all %}
    <button id="follow-button" data-id="{{puser.id}}"
      class="fa fa-minus-circle btn btn-warning btn-block">Follow</button>
    {% else %}
    <button id="follow-button" data-id="{{puser.id}}"
      class="fa fa-plus-circle btn btn-success btn-block">Follow</button>
    {% endif %}
  </div>
  {% endif %}
  <hr>
  <h2 class="BHS">{{puser.last_name}}{{puser.first_name}}님이 담은 영화</h2>
  <div class="row">
    {% for movie in puser.like_movies.all %}
    <div class="col-lg-6 card mb-3">
      <div class="row no-gutters">
        <div class="col-3">
          <a href="{% url 'movies:detail' movie.id %}"><img src="{{movie.poster_url}}" class="card-img"
              alt="{{movie.title}}"></a>
        </div>
        <div class="col-9">
          <div class="card-body">
            <h5 class="BHS card-title"><a href="{% url 'movies:detail' movie.id %}">{{movie.title}}</a></h5>
            <p class="card-text">리뷰 :
              {% for review in puser.review_set.all %}
              {% if review.movie_id == movie.id %}
              {{review.content}} <br>
              {% endif %}
              {% endfor %}
            </p>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  <hr style="color:black">
  <table class="table BHS">
    <h3 class="BHS">Following 유저 목록</h3>
    <thead>
      <tr>
        <th scope="col">아이디</th>
        <th scope="col">이름</th>
        <th scope="col">이메일</th>
      </tr>
    </thead>
    <tbody>
      {% for user in puser.followers.all %}
      <tr>
        <td><a href="{% url 'accounts:detail' user.id %}">{{user.username}}</a></td>
        <td><a href="{% url 'accounts:detail' user.id %}">{{user.last_name}}{{user.first_name}}</a></td>
        <td><a href="{% url 'accounts:detail' user.id %}">{{user.email}}</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <table class="table BHS">
    <h3 class="BHS">Follower 유저 목록</h3>
    <thead>
      <tr>
        <th scope="col">아이디</th>
        <th scope="col">이름</th>
        <th scope="col">이메일</th>
      </tr>
    </thead>
    <tbody>
      {% for user in puser.followings.all %}
      <tr>
        <td><a href="{% url 'accounts:detail' user.id %}">{{user.username}}</a></td>
        <td><a href="{% url 'accounts:detail' user.id %}">{{user.last_name}}{{user.first_name}}</a></td>
        <td><a href="{% url 'accounts:detail' user.id %}">{{user.email}}</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

{% block script %}
<script>
  const followbutton = document.querySelector('#follow-button')
  const followercount = document.querySelector('#follow-count')
  followbutton.addEventListener('click', function (event) {
    console.log(event.target)
    axios.defaults.xsrfCookieName = 'csrftoken'
    axios.defaults.xsrfHeaderName = 'X-CSRFToken'
    axios.defaults.headers.common['X-REQUESTED-WITH'] = 'XMLHttpRequest'
    axios.post(`/accounts/${event.target.dataset.id}/follow/`)
      .then(response => {
        console.log(response.data)
        console.log(event.target)
        if (response.data.is_followed) {
          event.target.classList.remove('btn-success')
          event.target.classList.add('btn-warning')
          event.target.classList.remove('fa-plus-circle')
          event.target.classList.add('fa-minus-circle')
        } else {
          event.target.classList.remove('btn-warning')
          event.target.classList.add('btn-success')
          event.target.classList.remove('fa-minus-circle')
          event.target.classList.add('fa-plus-circle')
        }
        followercount.innerText = `${response.data.count}`
      })
      .catch(error => {
        console.log(error)
      })
  })
</script>
{% endblock %}

accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% block body %}
{% for user in users %}
<p><a href="{% url 'accounts:detail' user.pk %}">{{user.username}}</a></p>
{% endfor %}
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static%}
{% block body %}
<div style=" height:100vh; background-position: center; background-image: url({% static 'movies/star.gif'%})">
  <div class="container text-center" style="width:350px; height:100%;padding-top:300px">
    <div class="" style="color:white;">
      <form class="BHS" action="" method='POST'>
        {% csrf_token %}
        {{form.as_p}}
        <button onclick="location.href='{% url 'accounts:signup' %}'" class="BHS btn btn-secondary">회원가입</button>
        <button class="BHS btn btn-secondary" type="submit">로그인</button>
      </form>
    </div>
  </div>
</div>
{% endblock  %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static%}
{% block body %}
<div style=" height:100vh; background-position: center; background-image: url({% static 'movies/star.gif'%})">
  <div class="container text-center px-auto" style="width:100%; height:100%; padding-top:200px">
    <div class="" style="color:white;">
      <form class="BHS" action="" method="POST">
        {% csrf_token %}
        <p><label for="id_username">사용자 이름:</label> <input type="text" name="username" maxlength="150" autofocus=""
            required="" id="id_username"></p>
        <p><label for="id_email">이메일 주소:</label> <input type="email" name="email" maxlength="254" id="id_email"></p>
        <p><label for="id_first_name">이름:</label> <input type="text" name="first_name" maxlength="30"
            id="id_first_name"></p>
        <p><label for="id_last_name">성:</label> <input type="text" name="last_name" maxlength="150" id="id_last_name">
        </p>
        <p><label for="id_password1">비밀번호:</label> <input type="password" name="password1" required=""
            id="id_password1"></p>
        <p><label for="id_password2">비밀번호 확인:</label> <input type="password" name="password2" required=""
            id="id_password2"> <span class="helptext"><br>확인을 위해 이전과 동일한 비밀번호를 입력하세요. </span></p>
        <button class="BHS btn btn-secondary" type="submit">회원가입</button>
      </form>
    </div>
  </div>
</div>
{% endblock  %}